name: Lint
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  lint-yml:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
          cache-dependency-path: "**/*.sum"
      - name: Setup yamlfmt
        working-directory: tools
        run: go install github.com/google/yamlfmt/cmd/yamlfmt
      - name: Verify YAML files format
        run: |
          yamlfmt -lint
